@PollyDemo.ResilientApi_HostAddress = https://localhost:5002

GET {{PollyDemo.ResilientApi_HostAddress}}/api/weather
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/retry/constant
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/retry/linear
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/retry/exponential
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/retry/selective
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/retry/retry-after
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/circuitbreaker/weather
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/timeout/weather
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/fallback/weather
Accept: application/json

###

GET {{PollyDemo.ResilientApi_HostAddress}}/api/timeout-fallback/weather
Accept: application/json

###
